apiVersion: v1
kind: ConfigMap
metadata:
  name: rumi-restaurant-web-config
  namespace: default
  labels:
    app: rumi-restaurant-web
data:
  NODE_ENV: "production"
  NEXT_TELEMETRY_DISABLED: "1"
  PORT: "3000"
  HOSTNAME: "0.0.0.0"
  # Add your environment variables here
  # NEXT_PUBLIC_API_URL: "https://your-api-domain.com"
  # NEXT_PUBLIC_APP_URL: "https://your-app-domain.com"
