apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rumi-production

resources:
- ../../

patchesStrategicMerge:
- deployment-patch.yaml
- ingress-patch.yaml

replicas:
- name: rumi-restaurant-web
  count: 5

images:
- name: rumi-restaurant-web
  newTag: v1.0.0

commonLabels:
  environment: production
