/**
 * Mailpit helper — read sent emails from the local SMTP catcher.
 *
 * The dev compose runs Mailpit at http://localhost:8025 (SMTP at :1025); the
 * backend points at it via `EmailSettings__SmtpHost=localhost`,
 * `EmailSettings__SmtpPort=1025`, `EmailSettings__UseAuthentication=false`.
 *
 * Tests use this helper to fetch the verification email backend just sent,
 * pull the verify URL out of the body, and drive the real UI verify flow —
 * exactly what a user would do.
 */

const MAILPIT_BASE_URL = process.env.E2E_MAILPIT_URL ?? 'http://localhost:8025';

interface MailpitMessageSummary {
  ID: string;
  To: { Address: string }[];
  Subject: string;
  Created: string;
}

interface MailpitSearchResponse {
  messages: MailpitMessageSummary[];
}

interface MailpitMessage {
  ID: string;
  HTML: string;
  Text: string;
  Subject: string;
  To: { Address: string }[];
}

interface WaitOptions {
  /** Total time to wait, in ms. Default 15s — covers SMTP send + indexing. */
  timeoutMs?: number;
  /** Poll interval, in ms. Default 500ms. */
  intervalMs?: number;
  /** Filter by subject (case-insensitive substring). */
  subjectIncludes?: string;
}

/**
 * Poll Mailpit until an email addressed to `email` arrives, then return the
 * first verification URL found in its HTML body.
 *
 * The verify URL format is generated by the backend in
 * `EmailService.SendEmailVerificationAsync`:
 *   {EmailSettings.FrontendBaseUrl}/verify-email?token=...&email=...
 */
export async function waitForVerificationLink(
  email: string,
  opts: WaitOptions = {},
): Promise<string> {
  const { timeoutMs = 15_000, intervalMs = 500, subjectIncludes } = opts;
  const deadline = Date.now() + timeoutMs;

  while (Date.now() < deadline) {
    const message = await findMessage(email, subjectIncludes);
    if (message) {
      const url = extractVerifyUrl(message);
      if (url) return url;
      throw new Error(
        `verification email arrived for ${email} but contained no /verify-email link. ` +
          `Subject: "${message.Subject}". HTML preview: ${message.HTML.slice(0, 300)}`,
      );
    }
    await sleep(intervalMs);
  }

  throw new Error(
    `Timed out after ${timeoutMs}ms waiting for verification email to ${email}. ` +
      `Is the backend pointed at Mailpit (EmailSettings__SmtpHost=localhost, SmtpPort=1025)?`,
  );
}

/**
 * Delete every message in Mailpit. Cheap and worker-safe — Mailpit is
 * single-tenant in our dev setup. Callers may use this in `beforeAll` /
 * `afterAll` if they want a quiet inbox; the auth fixture/test isolates by
 * recipient address so it isn't strictly required.
 */
export async function clearMailpit(): Promise<void> {
  const res = await fetch(`${MAILPIT_BASE_URL}/api/v1/messages`, { method: 'DELETE' });
  if (!res.ok) {
    throw new Error(`mailpit clear failed: ${res.status} ${await res.text()}`);
  }
}

async function findMessage(email: string, subjectIncludes?: string): Promise<MailpitMessage | null> {
  // Mailpit search syntax: `to:` for recipient. Newest first by default.
  const query = encodeURIComponent(`to:${email}`);
  const listRes = await fetch(`${MAILPIT_BASE_URL}/api/v1/search?query=${query}&limit=10`);
  if (!listRes.ok) {
    throw new Error(`mailpit search failed: ${listRes.status} ${await listRes.text()}`);
  }
  const list = (await listRes.json()) as MailpitSearchResponse;

  const candidate = list.messages.find((m) =>
    !subjectIncludes ? true : m.Subject.toLowerCase().includes(subjectIncludes.toLowerCase()),
  );
  if (!candidate) return null;

  const fullRes = await fetch(`${MAILPIT_BASE_URL}/api/v1/message/${candidate.ID}`);
  if (!fullRes.ok) {
    throw new Error(`mailpit fetch failed: ${fullRes.status} ${await fullRes.text()}`);
  }
  return (await fullRes.json()) as MailpitMessage;
}

function extractVerifyUrl(message: MailpitMessage): string | null {
  // Match the FrontendBaseUrl-prefixed verify link, including encoded query
  // params (token + email). The backend builds it via Uri.EscapeDataString,
  // so parens, slashes, and `=` are URL-safe; we only need to stop at
  // whitespace or a closing tag.
  const haystack = `${message.HTML}\n${message.Text}`;
  const match = haystack.match(/https?:\/\/[^\s"'<>]*\/verify-email\?[^\s"'<>]+/);
  return match ? match[0] : null;
}

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}
